version: '2'
services:
    test_server-app:
        image: test_server
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://test_server-mysql:3306/test_server?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    test_server-mysql:
        extends:
            file: mysql.yml
            service: test_server-mysql
